### ISSUE TITLE
Add app per team

### ISSUE THREAD

**Issue by digieon** [NewFuture/custom-stickers-teams-extension#13]
I notice other apps have the ability to be enabled for the whole team. It would be great if other team members can access stickers that are uploaded.

![image](https://user-images.githubusercontent.com/52335116/89457418-5d7d0600-d733-11ea-8a8d-5f2af4fc2438.png)

**Comment by NewFuture** [comment]
Thanks. it's a good idea. but I prefer it to be a personal app at present.

If you install it means that you have read the privacy and user teams and allowed this app to store **YOUR** stickers.
while your team members may not realize that their stickers will store in our server when they upload images. 

I think that reading the permission statements and confirming are needed for every user.


And I will continue to consider a better way to combine it with a team. thank you very much.

**Comment by NewFuture** [comment]
Now we support org-wide management. But there is still no plan for team-wide.
