### ISSUE TITLE
Bug found

### ISSUE THREAD

**Issue by v-roche** [NewFuture/custom-stickers-teams-extension#20]
Hi team,

It seems to be some bug that we are unable to access the app after downloading it. It shows "Unable to reach app. Please try again." as we tried to use it. Could you please check it for us? 

Thanks a million in advance.

Best regards,
Rocky

**Comment by v-roche** [comment]
One more question, would it be possible to know how many times the sticker designed is downloaded? If yes, how could we find it?

**Comment by NewFuture** [comment]
Thanks for your feedback.
The SSL cert is expired in some regions and updated now.
Thank you again.

**Comment by NewFuture** [comment]
> One more question, would it be possible to know how many times the sticker designed is downloaded?

Sorry, it doesn't have this feature.
