### ISSUE TITLE
Automatic resizing

### ISSUE THREAD

**Issue by raldone01** [NewFuture/custom-stickers-teams-extension#3]
It would be awesome if too large images resolution would be reduced automatically.

**Comment by NewFuture** [comment]
Yes, we also want this feature.
But, now ,it was limited by the Image Card in Teams which could not set the size of the card.

**Comment by raldone01** [comment]
Can't you crop it when its uploaded?

**Comment by onenzz** [comment]
I would say downsize images and not crop them.
Automatic cropping would lead to issues.

**Comment by NewFuture** [comment]
> I would say downsize images and not crop them.

agree with you

**Comment by onenzz** [comment]
Is there any way to adjust the card size? I have my stickers set to 64 x 64 pixels but each image card is a lot wider than that.

**Comment by NewFuture** [comment]
It auto-resize in v2 now
