### ISSUE TITLE
webp support

### ISSUE THREAD

**Issue by raldone01** [NewFuture/custom-stickers-teams-extension#4]
Manually adding webp files works properly but they don't show up when they are sent!

**Comment by NewFuture** [comment]
Thanks for your feedback.

Did you use it in MacOS or iOS ?

As I know, webp images are not support in iOS now.

https://discussions.apple.com/thread/250073758

**Comment by raldone01** [comment]
I used windows.

**Comment by NewFuture** [comment]
wbp will covert in V2 #84

**Comment by NewFuture** [comment]
webp will be convert to png now
