### ISSUE TITLE
How can I export all image from this extension?

### ISSUE THREAD

**Issue by zmcx16** [NewFuture/custom-stickers-teams-extension#43]
Hello,
I would like to export all images from this extension for backup, is there any solution for this requirement? thanks.

**Comment by NewFuture** [comment]
you can open the teams in  browsers , 
then right click the stikcer icon,
next open settings page , and save the images one by one.

**Comment by zmcx16** [comment]
Hi NewFuture,

Thanks for the reply, I found a quick solution base on your suggestion.
After opening the settings page from the web browser, we can press ctrl+s to store full html & resources, the all images and html, css will be stored on the target folder.
btw, if the image is added from other people sticker rather than import by yourself, the store image file name will be imgo, imgo(1), imgo(2)..., need to rename it manually (add .jpg)
