### ISSUE TITLE
Suggestion-Any chance to allow more pics to be uploaded? 

### ISSUE THREAD

**Issue by wax951223** [NewFuture/custom-stickers-teams-extension#45]
It seems the limit is 100 pics, any chance to increase the total amount? Thx~

**Comment by NewFuture** [comment]
Yes. it's 100 at present. 
How many images do you want to save?

The number is a balance for `query performance`, `server cost`, and `user requirements`.

**Comment by NewFuture** [comment]
The v2 version was published you can upload 150 pics now
