### ISSUE TITLE
add more stickers after the first connection to the application

### ISSUE THREAD

**Issue by sagivy** [NewFuture/custom-stickers-teams-extension#5]
Hi Guys,
How do I upload more stickers after I installed the application?
in the first run, it prompts me for upload field but after you close that window you cannot upload anymore.

Also, does it support sticker names in every language or only English?

![sticker](https://user-images.githubusercontent.com/43612027/81284066-49f3cd80-9066-11ea-9316-7cf55a4af6ca.PNG)

**Comment by NewFuture** [comment]
### For upload/management your  stickers
1. right-click the ♥ icon 
2. click the `configuration/setting`  in the menu (the second item)

### For languages
You can use any language as you want even emojis for the name and searching.
