### ISSUE TITLE
Why can't I add more custom stickers after I already uploaded some??

### ISSUE THREAD

**Issue by cedrodkcz** [NewFuture/custom-stickers-teams-extension#52]
Title. When there are no stickers uploaded yet it will ask you to add some but once you've done that the option to add more is gone. (also to clarify I am trying to add new stickers from my files, not by saving other people's stickers)

**Comment by NewFuture** [comment]
right-click the ♥ icon in the bar. 
Then, click the `configure` or `settings` button.
