### ISSUE TITLE
The popup to upload stickers doesn't stop the loading screen

### ISSUE THREAD

**Issue by goncalo42220** [NewFuture/custom-stickers-teams-extension#59]
![image](https://user-images.githubusercontent.com/26144866/141988073-78589c9c-6be1-4f3d-bac8-bbf92d1600e3.png)

**Comment by NewFuture** [comment]
Thanks for your feedback.
It maybe a bug of Teams client https://github.com/OfficeDev/microsoft-teams-library-js/issues/680

**Comment by NewFuture** [comment]
fixed
