### ISSUE TITLE
can't upload to microsoft team

### ISSUE THREAD

**Issue by leovlad1** [NewFuture/custom-stickers-teams-extension#78]
hi, I can't upload my sitcker to microsoft team, still loading, help me pls
![image](https://user-images.githubusercontent.com/105028083/167116756-f3dc58eb-38f0-40d7-9d10-76392b6d0b14.png)

**Comment by NewFuture** [comment]
it's a known bug in teams auth. i will change the way for auth later

**Comment by NewFuture** [comment]
fixed

**Comment by leovlad1** [comment]
still loading on desktop client , please see detail 
![image](https://user-images.githubusercontent.com/105028083/168731017-2d6b8eec-e79b-4207-87de-577bec198988.png)


> fixed

**Comment by NewFuture** [comment]
@leovlad1  the old page is cached in your teams.
you can clear the Teams cache manually https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-administration/clear-teams-cache
