### ISSUE TITLE
Stuck on setup

### ISSUE THREAD

**Issue by biancabonilla** [NewFuture/custom-stickers-teams-extension#8]
Upon clicking Open, the following message is displayed: You'll need to set up this app to use all of its features.
 The words set up are underlined and seem to be a link but no matter how many times I click on it, it does nothing. How can I "set up" the app to use it?
[Doc1.docx](https://github.com/NewFuture/custom-stickers-teams-extension/files/4794831/Doc1.docx)

**Comment by NewFuture** [comment]
Sorry for the late reply.
Just click the `set up` link, it will popup a new Teams window for upload images as stickers.
