### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by bogomazdmitry** [NewFuture/custom-stickers-teams-extension#80]
Sorry, do you have any documentation for building your extention? I want to add some feature, but I don't understand how to build :)

**Comment by NewFuture** [comment]
sorry for the incomplete documentation.

create a file `.env` in the root folder for configuration 
```
MICROSOFT_APP_ID='BOT ID'
HOSTNAME='backend API'
WEB_HOST=WEB domain
AZURE_STORAGE_CDN=Blob Domain
TEAMS_APP_ID= 'APP ID'
```

* `yarn manifest` to generate the manifest file
* `yarn server` to start the server (backend API + webpage) 
* `yarn web` to start the web dev server (front-end)

> it's difficult to debug bot and storage at current.
> you need some tools like ngrok to debug it in teams with bot
