### ISSUE TITLE
UNABLE TO UPLOAD STICKERS IN TEAMS WITH CUSTOM APP

### ISSUE THREAD

**Issue by AliZULEKHA** [NewFuture/custom-stickers-teams-extension#83]
Hi
I am not able to upload stickers in custom app in teams. Please help to resolve this so I can use this feature.
![custom app](https://user-images.githubusercontent.com/112097717/186689397-ff867ef1-cd62-4390-956d-b6085bc4609a.PNG)

**Comment by NewFuture** [comment]
seems a bug in the New Teams client.

But you can upload by right click

![image](https://user-images.githubusercontent.com/6290356/186813670-587c7f86-0b2b-4c59-a2a0-b12c08aba225.png)

**Comment by AliZULEKHA** [comment]
Thank you for your help this option is working…

**Comment by NewFuture** [comment]
we change the entry in v2 version
